import { Course, User } from "@/types"

export const user: User = {
  id: "1",
  name: "John Doe",
  email: "john.doe@example.com",
  avatar: "/placeholder.svg?height=40&width=40",
  enrolledCourses: ["1", "2", "3"],
  wishlist: ["4", "5"],
  progress: [
    { courseId: "1", progress: 75, lastAccessed: "2024-01-15" },
    { courseId: "2", progress: 30, lastAccessed: "2024-01-14" },
    { courseId: "3", progress: 100, lastAccessed: "2024-01-10" },
  ],
  achievements: ["first-course", "week-streak"],
  preferences: {
    language: "en",
    autoplay: true,
    quality: "auto",
  },
}

export const courses: Course[] = [
  {
    id: "1",
    title: "Complete React Developer Course",
    description:
      "Learn React from scratch with hands-on projects and real-world applications. Master components, hooks, state management, and modern React patterns.",
    instructor: { name: "Sarah Johnson", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 2400,
    lectures: [
      { id: "1", title: "Introduction to React", duration: 300, completed: true },
      { id: "2", title: "Components and Props", duration: 450, completed: true },
      { id: "3", title: "State and Lifecycle", duration: 600, completed: false },
    ],
    rating: 4.8,
    price: 89.99,
    category: "Web Development",
    level: "Intermediate",
    language: "English",
  },
  {
    id: "2",
    title: "JavaScript Fundamentals",
    description:
      "Master JavaScript basics and advanced concepts including ES6+, async programming, and modern JavaScript development practices.",
    instructor: { name: "Mike Chen", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 1800,
    lectures: [
      { id: "1", title: "Variables and Data Types", duration: 240, completed: true },
      { id: "2", title: "Functions and Scope", duration: 360, completed: false },
    ],
    rating: 4.6,
    price: 69.99,
    category: "Programming",
    level: "Beginner",
    language: "English",
  },
  {
    id: "3",
    title: "UI/UX Design Masterclass",
    description:
      "Complete guide to user interface and experience design. Learn design principles, user research, prototyping, and design systems.",
    instructor: { name: "Emma Wilson", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 3000,
    lectures: [
      { id: "1", title: "Design Principles", duration: 400, completed: true },
      { id: "2", title: "User Research", duration: 500, completed: true },
      { id: "3", title: "Prototyping", duration: 600, completed: true },
    ],
    rating: 4.9,
    price: 129.99,
    category: "Design",
    level: "Advanced",
    language: "English",
  },
  {
    id: "4",
    title: "Python for Data Science",
    description:
      "Learn Python programming for data analysis and machine learning. Cover pandas, numpy, matplotlib, and scikit-learn.",
    instructor: { name: "David Kumar", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 2700,
    lectures: [],
    rating: 4.7,
    price: 99.99,
    category: "Data Science",
    level: "Intermediate",
    language: "English",
  },
  {
    id: "5",
    title: "Digital Marketing Strategy",
    description:
      "Complete digital marketing course for beginners. Learn SEO, social media marketing, content marketing, and analytics.",
    instructor: { name: "Lisa Rodriguez", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 2100,
    lectures: [],
    rating: 4.5,
    price: 79.99,
    category: "Marketing",
    level: "Beginner",
    language: "English",
  },
  {
    id: "6",
    title: "Machine Learning Fundamentals",
    description:
      "Introduction to machine learning concepts, algorithms, and practical applications using Python and popular ML libraries.",
    instructor: { name: "Alex Thompson", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 3200,
    lectures: [],
    rating: 4.8,
    price: 149.99,
    category: "Data Science",
    level: "Advanced",
    language: "English",
  },
  {
    id: "7",
    title: "Mobile App Development with Flutter",
    description:
      "Build cross-platform mobile applications using Flutter and Dart. Learn widgets, state management, and app deployment.",
    instructor: { name: "Jennifer Lee", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 2800,
    lectures: [],
    rating: 4.6,
    price: 119.99,
    category: "Mobile Development",
    level: "Intermediate",
    language: "English",
  },
  {
    id: "8",
    title: "Cloud Computing with AWS",
    description:
      "Master Amazon Web Services cloud platform. Learn EC2, S3, Lambda, and other essential AWS services for modern applications.",
    instructor: { name: "Robert Kim", avatar: "/placeholder.svg?height=32&width=32" },
    thumbnail: "/placeholder.svg?height=200&width=300",
    duration: 2600,
    lectures: [],
    rating: 4.7,
    price: 139.99,
    category: "Cloud Computing",
    level: "Intermediate",
    language: "English",
  },
]