
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "frontend"

[services.source]
repo = "your-repo-url"
branch = "main"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{BACKEND_URL}}"
